import type { Template } from './types';

export const templates: Template[] = [
  {
    id: 'animated-developer',
    name: 'Animated Developer',
    description: 'Eye-catching profile with animated header, typing effect, and full stats',
    thumbnail: '/templates/animated.png',
    blocks: [
      {
        id: 'tpl-1',
        type: 'capsule-header',
        props: {
          text: 'Welcome to my GitHub!',
          type: 'waving',
          height: 200,
          section: 'header',
          bgType: 'gradient',
          bgGradientDirection: 'horizontal',
          bgAnimation: 'none',
          bgStartColor: '36BCF7',
          bgEndColor: '6B5DD3',
          bgSolidColor: '36BCF7',
          fontColor: 'ffffff',
          fontSize: 30,
          parallaxEffect: true,
          wavePosition: 70,
          waveAmplitude: 20,
          waveSpeed: 20,
          waveFlip: true,
          textAlignX: 50,
          textAlignY: 33,
        },
      },
      {
        id: 'tpl-2',
        type: 'greeting',
        props: {
          text: "Hi there, I'm John Doe!",
          emoji: '👋',
          alignment: 'center',
        },
      },
      {
        id: 'tpl-3',
        type: 'typing-animation',
        props: {
          lines: ['Full Stack Developer', 'Open Source Enthusiast', 'Always Learning'],
          color: '36BCF7',
          width: 435,
          height: 30,
          speed: 50,
        },
      },
      {
        id: 'tpl-4',
        type: 'spacer',
        props: { height: 20 },
      },
      {
        id: 'tpl-5',
        type: 'heading',
        props: {
          text: 'About Me',
          level: 2,
          alignment: 'center',
          emoji: '🚀',
        },
      },
      {
        id: 'tpl-6',
        type: 'paragraph',
        props: {
          text: "I'm a passionate developer who loves building things that live on the internet. I specialize in creating exceptional digital experiences that are fast, accessible, and visually appealing.",
          alignment: 'center',
        },
      },
      {
        id: 'tpl-7',
        type: 'heading',
        props: {
          text: 'Tech Stack',
          level: 2,
          alignment: 'center',
          emoji: '💻',
        },
      },
      {
        id: 'tpl-8',
        type: 'skill-icons',
        props: {
          icons: [
            'js',
            'ts',
            'react',
            'nextjs',
            'nodejs',
            'python',
            'docker',
            'aws',
            'git',
            'vscode',
          ],
          perLine: 10,
          theme: 'dark',
        },
      },
      {
        id: 'tpl-9',
        type: 'heading',
        props: {
          text: 'GitHub Stats',
          level: 2,
          alignment: 'center',
          emoji: '📊',
        },
      },
      {
        id: 'tpl-10',
        type: 'stats-row',
        props: {
          direction: 'row',
          gap: 12,
          cardWidth: '49%',
          cardHeight: 230,
          theme: 'tokyonight',
          hideBorder: false,
        },
        children: [
          {
            id: 'tpl-10a',
            type: 'stats-card',
            props: {
              username: 'github',
              theme: 'tokyonight',
              layoutStyle: 'standard',
              showIcons: true,
              hideBorder: false,
              hideTitle: false,
              hideRank: false,
              borderRadius: 10,
              layoutWidth: 'half',
            },
          },
          {
            id: 'tpl-10b',
            type: 'top-languages',
            props: {
              username: 'github',
              theme: 'tokyonight',
              layout: 'compact',
              hideBorder: false,
              hideProgress: false,
              langs_count: 8,
              borderRadius: 10,
              layoutWidth: 'half',
            },
          },
        ],
      },
      {
        id: 'tpl-11',
        type: 'streak-stats',
        props: {
          username: 'github',
          theme: 'tokyonight',
          hideBorder: false,
          borderRadius: 10,
          layoutWidth: 'full',
        },
      },
      {
        id: 'tpl-13',
        type: 'heading',
        props: {
          text: 'Connect with Me',
          level: 2,
          alignment: 'center',
          emoji: '🤝',
        },
      },
      {
        id: 'tpl-14',
        type: 'social-badges',
        props: {
          linkedin: 'johndoe',
          twitter: 'johndoe',
          github: 'johndoe',
          email: 'john@example.com',
          youtube: '',
          instagram: '',
          discord: '',
          portfolio: '',
          style: 'for-the-badge',
        },
      },
      {
        id: 'tpl-15',
        type: 'visitor-counter',
        props: {
          username: 'johndoe',
          color: 'blue',
          style: 'flat',
          label: 'Profile Views',
        },
      },
      {
        id: 'tpl-16',
        type: 'footer-banner',
        props: {
          text: 'Thanks for visiting!',
          type: 'waving',
          section: 'footer',
          height: 120,
          fontSize: 24,
          fontColor: 'ffffff',
          bgType: 'gradient',
          bgGradientDirection: 'horizontal',
          bgAnimation: 'none',
          bgStartColor: '36BCF7',
          bgEndColor: '6B5DD3',
          bgSolidColor: '36BCF7',
          parallaxEffect: true,
          wavePosition: 70,
          waveAmplitude: 20,
          waveSpeed: 20,
          waveFlip: true,
          textAlignX: 50,
          textAlignY: 66,
        },
      },
    ],
  },

  {
    id: 'minimal-clean',
    name: 'Minimal Clean',
    description: 'Simple and elegant profile with essential information',
    thumbnail: '/templates/minimal.png',
    blocks: [
      {
        id: 'min-1',
        type: 'greeting',
        props: {
          text: 'Hello, World!',
          emoji: '👋',
          alignment: 'left',
        },
      },
      {
        id: 'min-2',
        type: 'paragraph',
        props: {
          text: "I'm a software developer passionate about creating elegant solutions to complex problems.",
          alignment: 'left',
        },
      },
      {
        id: 'min-3',
        type: 'divider',
        props: {
          type: 'line',
          bgType: 'solid',
          bgSolidColor: 'E1E4E8',
          bgStartColor: 'E1E4E8',
          bgEndColor: 'C8CCD0',
          bgGradientDirection: 'horizontal',
          thickness: 1,
          alignment: 'center',
        },
      },
      {
        id: 'min-4',
        type: 'heading',
        props: {
          text: 'What I do',
          level: 3,
          alignment: 'left',
        },
      },
      {
        id: 'min-5',
        type: 'paragraph',
        props: {
          text: '• Building web applications with React and Node.js\n• Contributing to open source projects\n• Writing technical blog posts',
          alignment: 'left',
        },
      },
      {
        id: 'min-6',
        type: 'divider',
        props: {
          type: 'line',
          bgType: 'solid',
          bgSolidColor: 'E1E4E8',
          bgStartColor: 'E1E4E8',
          bgEndColor: 'C8CCD0',
          bgGradientDirection: 'horizontal',
          thickness: 1,
          alignment: 'center',
        },
      },
      {
        id: 'min-7',
        type: 'stats-card',
        props: {
          username: 'github',
          theme: 'graywhite',
          layoutStyle: 'standard',
          layoutWidth: 'full',
          showIcons: true,
          hideBorder: true,
          hideTitle: false,
          hideRank: true,
          borderRadius: 5,
        },
      },
      {
        id: 'min-8',
        type: 'social-badges',
        props: {
          linkedin: 'username',
          github: 'username',
          email: 'email@example.com',
          twitter: '',
          youtube: '',
          instagram: '',
          discord: '',
          portfolio: '',
          style: 'flat',
        },
      },
    ],
  },

  {
    id: 'stats-focused',
    name: 'Stats Focused',
    description: 'Showcase your GitHub activity with comprehensive statistics',
    thumbnail: '/templates/stats.png',
    blocks: [
      {
        id: 'stat-1',
        type: 'heading',
        props: {
          text: 'GitHub Activity Dashboard',
          level: 1,
          alignment: 'center',
        },
      },
      {
        id: 'stat-2',
        type: 'paragraph',
        props: {
          text: 'A comprehensive view of my GitHub contributions and achievements',
          alignment: 'center',
        },
      },
      {
        id: 'stat-3',
        type: 'spacer',
        props: { height: 20 },
      },
      {
        id: 'stat-4',
        type: 'stats-row',
        props: {
          direction: 'row',
          gap: 12,
          cardWidth: '49%',
          cardHeight: 230,
          theme: 'radical',
          hideBorder: false,
        },
        children: [
          {
            id: 'stat-4a',
            type: 'stats-card',
            props: {
              username: 'github',
              theme: 'radical',
              layoutStyle: 'standard',
              showIcons: true,
              hideBorder: false,
              hideTitle: false,
              hideRank: false,
              borderRadius: 10,
              layoutWidth: 'half',
            },
          },
          {
            id: 'stat-4b',
            type: 'top-languages',
            props: {
              username: 'github',
              theme: 'radical',
              layout: 'donut',
              hideBorder: false,
              hideProgress: false,
              langs_count: 6,
              borderRadius: 10,
              layoutWidth: 'half',
            },
          },
        ],
      },
      {
        id: 'stat-5',
        type: 'streak-stats',
        props: {
          username: 'github',
          theme: 'radical',
          hideBorder: false,
          borderRadius: 10,
          layoutWidth: 'full',
        },
      },
      {
        id: 'stat-7',
        type: 'activity-graph',
        props: {
          username: 'github',
          theme: 'rogue',
          hideBorder: false,
        },
      },
      {
        id: 'stat-8',
        type: 'trophies',
        props: {
          username: 'github',
          theme: 'radical',
          column: 6,
          row: 1,
          margin_w: 15,
          margin_h: 15,
          noFrame: false,
          noBg: false,
        },
      },
    ],
  },

  {
    id: 'creative-profile',
    name: 'Creative Profile',
    description: 'Stand out with unique animations and creative elements',
    thumbnail: '/templates/creative.png',
    blocks: [
      {
        id: 'cre-1',
        type: 'capsule-header',
        props: {
          text: 'Creative Profile',
          type: 'cylinder',
          height: 150,
          section: 'header',
          bgType: 'gradient',
          bgGradientDirection: 'horizontal',
          bgAnimation: 'wave',
          bgStartColor: 'EEFF00',
          bgEndColor: 'A82DAA',
          bgSolidColor: 'EEFF00',
          fontColor: 'ffffff',
          fontSize: 30,
          parallaxEffect: false,
          wavePosition: 70,
          waveAmplitude: 20,
          waveSpeed: 20,
          waveFlip: false,
          textAlignX: 50,
          textAlignY: 50,
        },
      },
      {
        id: 'cre-2',
        type: 'avatar',
        props: {
          imageUrl: 'https://github.com/github.png',
          size: 150,
          borderRadius: 50,
          borderColor: '',
        },
      },
      {
        id: 'cre-3',
        type: 'greeting',
        props: {
          text: "Hey! I'm a Creative Developer",
          emoji: '✨',
          alignment: 'center',
        },
      },
      {
        id: 'cre-4',
        type: 'typing-animation',
        props: {
          lines: ['Designer', 'Developer', 'Creator', 'Innovator'],
          color: 'FF6B6B',
          width: 400,
          height: 35,
          speed: 50,
          center: true,
          vCenter: true,
        },
      },
      {
        id: 'cre-5',
        type: 'quote',
        props: {
          quote: 'Design is not just what it looks like, design is how it works.',
          author: 'Steve Jobs',
          theme: 'dracula',
          textAlign: 'center',
          authorAlign: 'center',
        },
      },
      {
        id: 'cre-6',
        type: 'heading',
        props: {
          text: 'My Creative Stack',
          level: 2,
          alignment: 'center',
          emoji: '🎨',
        },
      },
      {
        id: 'cre-7',
        type: 'skill-icons',
        props: {
          icons: ['figma', 'ai', 'ps', 'blender', 'react', 'tailwind', 'nextjs', 'ts'],
          perLine: 8,
          theme: 'dark',
        },
      },
      {
        id: 'cre-8',
        type: 'stats-card',
        props: {
          username: 'github',
          theme: 'dracula',
          layoutStyle: 'standard',
          layoutWidth: 'full',
          showIcons: true,
          hideBorder: false,
          hideTitle: false,
          hideRank: false,
          borderRadius: 15,
        },
      },
      {
        id: 'cre-9',
        type: 'footer-banner',
        props: {
          text: "Let's create something amazing!",
          type: 'waving',
          section: 'footer',
          height: 100,
          fontSize: 24,
          fontColor: 'ffffff',
          bgType: 'gradient',
          bgGradientDirection: 'diagonal',
          bgAnimation: 'none',
          bgStartColor: 'FF6B6B',
          bgEndColor: 'A82DAA',
          bgSolidColor: 'FF6B6B',
          parallaxEffect: true,
          wavePosition: 70,
          waveAmplitude: 20,
          waveSpeed: 20,
          waveFlip: true,
          textAlignX: 50,
          textAlignY: 66,
        },
      },
    ],
  },

  {
    id: 'open-source-maintainer',
    name: 'Open Source Maintainer',
    description:
      'Built for OSS contributors — trophies, full activity graph, and collapsible project highlights',
    thumbnail: '/templates/opensource.png',
    blocks: [
      {
        id: 'oss-1',
        type: 'capsule-header',
        props: {
          text: 'Open Source Maintainer',
          type: 'waving',
          height: 180,
          section: 'header',
          bgType: 'gradient',
          bgGradientDirection: 'vertical',
          bgAnimation: 'none',
          bgStartColor: '3370cc',
          bgEndColor: '161B22',
          bgSolidColor: '3370cc',
          fontColor: 'ffffff',
          fontSize: 30,
          parallaxEffect: true,
          wavePosition: 70,
          waveAmplitude: 20,
          waveSpeed: 20,
          waveFlip: true,
          textAlignX: 50,
          textAlignY: 27,
        },
      },
      {
        id: 'oss-2a',
        type: 'avatar',
        props: {
          imageUrl: 'https://github.com/github.png',
          size: 120,
          borderRadius: 50,
          borderColor: '',
        },
      },
      {
        id: 'oss-2b',
        type: 'greeting',
        props: {
          text: 'Hey, I build things for the community',
          emoji: '🛠️',
          alignment: 'center',
        },
      },
      {
        id: 'oss-3',
        type: 'typing-animation',
        props: {
          lines: ['Open Source Contributor', 'Library Author', 'Bug Squasher', 'Community Builder'],
          color: '58A6FF',
          width: 480,
          height: 30,
          speed: 50,
        },
      },
      {
        id: 'oss-4',
        type: 'social-badges',
        props: {
          github: 'yourusername',
          twitter: 'yourusername',
          email: 'you@example.com',
          linkedin: '',
          youtube: '',
          instagram: '',
          discord: '',
          portfolio: '',
          style: 'for-the-badge',
        },
      },
      {
        id: 'oss-5',
        type: 'divider',
        props: {
          type: 'line',
          bgType: 'solid',
          bgSolidColor: '30363D',
          bgStartColor: '30363D',
          bgEndColor: '30363D',
          bgGradientDirection: 'horizontal',
          thickness: 1,
          alignment: 'center',
        },
      },
      {
        id: 'oss-6',
        type: 'heading',
        props: {
          text: 'About Me',
          level: 2,
          alignment: 'left',
          emoji: '👤',
        },
      },
      {
        id: 'oss-7',
        type: 'paragraph',
        props: {
          text: "I'm passionate about open-source software and believe in the power of collaborative development. I maintain several widely-used libraries and am always looking for ways to give back to the community.",
          alignment: 'left',
        },
      },
      {
        id: 'oss-8',
        type: 'collapsible',
        props: { title: '🔥 Featured Projects', defaultOpen: true },
        children: [
          {
            id: 'oss-8a',
            type: 'paragraph',
            props: {
              text: '- **awesome-lib** — A utility library used by 10k+ developers\n- **cli-tool** — A developer productivity CLI with 5k+ stars\n- **docs-gen** — Auto documentation generator for TypeScript projects',
              alignment: 'left',
            },
          },
        ],
      },
      {
        id: 'oss-9',
        type: 'collapsible',
        props: { title: '📦 My Tech Stack', defaultOpen: false },
        children: [
          {
            id: 'oss-9a',
            type: 'skill-icons',
            props: {
              icons: [
                'ts',
                'nodejs',
                'rust',
                'go',
                'python',
                'docker',
                'kubernetes',
                'github',
                'linux',
                'bash',
              ],
              perLine: 10,
              theme: 'dark',
            },
          },
        ],
      },
      {
        id: 'oss-10',
        type: 'divider',
        props: {
          type: 'line',
          bgType: 'solid',
          bgSolidColor: '30363D',
          bgStartColor: '30363D',
          bgEndColor: '30363D',
          bgGradientDirection: 'horizontal',
          thickness: 1,
          alignment: 'center',
        },
      },
      {
        id: 'oss-11',
        type: 'heading',
        props: {
          text: 'Contribution Stats',
          level: 2,
          alignment: 'center',
          emoji: '📈',
        },
      },
      {
        id: 'oss-12',
        type: 'trophies',
        props: {
          username: 'github',
          theme: 'github_dark',
          column: 7,
          row: 2,
          margin_w: 10,
          margin_h: 10,
          noFrame: false,
          noBg: false,
        },
      },
      {
        id: 'oss-13',
        type: 'activity-graph',
        props: {
          username: 'github',
          theme: 'github_dark',
          hideBorder: true,
        },
      },
      {
        id: 'oss-14',
        type: 'stats-row',
        props: {
          direction: 'row',
          gap: 12,
          cardWidth: '49%',
          cardHeight: 230,
          theme: 'github_dark',
          hideBorder: false,
        },
        children: [
          {
            id: 'oss-14a',
            type: 'stats-card',
            props: {
              username: 'github',
              theme: 'github_dark',
              layoutStyle: 'standard',
              showIcons: true,
              hideBorder: false,
              hideTitle: false,
              hideRank: false,
              borderRadius: 8,
              layoutWidth: 'half',
            },
          },
          {
            id: 'oss-14b',
            type: 'top-languages',
            props: {
              username: 'github',
              theme: 'github_dark',
              layout: 'compact',
              hideBorder: false,
              hideProgress: false,
              langs_count: 10,
              borderRadius: 8,
              layoutWidth: 'half',
            },
          },
        ],
      },
      {
        id: 'oss-15',
        type: 'streak-stats',
        props: {
          username: 'github',
          theme: 'github_dark',
          hideBorder: false,
          borderRadius: 8,
          layoutWidth: 'full',
        },
      },
      {
        id: 'oss-17',
        type: 'divider',
        props: {
          type: 'line',
          bgType: 'solid',
          bgSolidColor: '30363D',
          bgStartColor: '30363D',
          bgEndColor: '30363D',
          bgGradientDirection: 'horizontal',
          thickness: 1,
          alignment: 'center',
        },
      },
      {
        id: 'oss-18',
        type: 'visitor-counter',
        props: {
          username: 'github',
          color: 'brightgreen',
          style: 'flat-square',
          label: 'Profile Views',
        },
      },
      {
        id: 'oss-19',
        type: 'footer-banner',
        props: {
          text: 'Happy to collaborate — open an issue or PR!',
          type: 'waving',
          section: 'footer',
          height: 100,
          fontSize: 24,
          fontColor: 'ffffff',
          bgType: 'gradient',
          bgGradientDirection: 'vertical',
          bgAnimation: 'none',
          bgStartColor: '3370cc',
          bgEndColor: '161B22',
          bgSolidColor: '3370cc',
          parallaxEffect: true,
          wavePosition: 70,
          waveAmplitude: 20,
          waveSpeed: 20,
          waveFlip: true,
          textAlignX: 50,
          textAlignY: 76,
        },
      },
    ],
  },

  {
    id: 'full-stack-engineer',
    name: 'Full Stack Engineer',
    description: 'Professional developer profile with comprehensive tech stack and GitHub stats',
    thumbnail: '/templates/full-stack.png',
    blocks: [
      {
        id: 'fse-1',
        type: 'capsule-header',
        props: {
          text: 'Full Stack Engineer',
          type: 'waving',
          height: 200,
          section: 'header',
          bgType: 'gradient',
          bgGradientDirection: 'horizontal',
          bgAnimation: 'wave',
          bgStartColor: 'CBA6F7',
          bgEndColor: '94E2D5',
          bgSolidColor: 'CBA6F7',
          fontColor: 'ffffff',
          fontSize: 30,
          parallaxEffect: false,
          wavePosition: 70,
          waveAmplitude: 20,
          waveSpeed: 20,
          waveFlip: false,
          textAlignX: 50,
          textAlignY: 50,
        },
      },
      {
        id: 'fse-2',
        type: 'greeting',
        props: {
          text: "I'm a Full Stack Engineer",
          emoji: '⚡',
          alignment: 'center',
        },
      },
      {
        id: 'fse-3',
        type: 'typing-animation',
        props: {
          lines: [
            'React · Next.js · TypeScript',
            'Node.js · PostgreSQL · Redis',
            'AWS · Docker · Kubernetes',
            'Building at scale since 2018',
          ],
          color: 'CBA6F7',
          width: 500,
          height: 30,
          speed: 50,
        },
      },
      {
        id: 'fse-4',
        type: 'paragraph',
        props: {
          text: 'I design and build end-to-end products — from pixel-perfect UIs to scalable distributed backends. I care deeply about developer experience, performance, and clean architecture.',
          alignment: 'center',
        },
      },
      {
        id: 'fse-5',
        type: 'social-badges',
        props: {
          linkedin: 'yourusername',
          twitter: 'yourusername',
          github: 'yourusername',
          email: 'hello@yoursite.dev',
          portfolio: 'https://yoursite.dev',
          youtube: '',
          instagram: '',
          discord: '',
          style: 'for-the-badge',
        },
      },
      {
        id: 'fse-6',
        type: 'divider',
        props: {
          type: 'line',
          bgType: 'gradient',
          bgGradientDirection: 'horizontal',
          bgStartColor: 'CBA6F7',
          bgEndColor: '94E2D5',
          bgSolidColor: 'CBA6F7',
          thickness: 2,
          alignment: 'center',
        },
      },
      {
        id: 'fse-7',
        type: 'heading',
        props: {
          text: 'Frontend',
          level: 2,
          alignment: 'center',
          emoji: '🎨',
        },
      },
      {
        id: 'fse-8',
        type: 'skill-icons',
        props: {
          icons: ['html', 'css', 'js', 'ts', 'react', 'nextjs', 'vue', 'tailwind', 'sass', 'figma'],
          perLine: 10,
          theme: 'dark',
        },
      },
      {
        id: 'fse-9',
        type: 'heading',
        props: {
          text: 'Backend & Databases',
          level: 2,
          alignment: 'center',
          emoji: '🗄️',
        },
      },
      {
        id: 'fse-10',
        type: 'skill-icons',
        props: {
          icons: [
            'nodejs',
            'express',
            'nestjs',
            'python',
            'fastapi',
            'postgres',
            'mysql',
            'mongodb',
            'redis',
            'graphql',
          ],
          perLine: 10,
          theme: 'dark',
        },
      },
      {
        id: 'fse-11',
        type: 'heading',
        props: {
          text: 'Cloud & DevOps',
          level: 2,
          alignment: 'center',
          emoji: '☁️',
        },
      },
      {
        id: 'fse-12',
        type: 'skill-icons',
        props: {
          icons: [
            'aws',
            'gcp',
            'azure',
            'docker',
            'kubernetes',
            'nginx',
            'github',
            'git',
            'linux',
            'bash',
          ],
          perLine: 10,
          theme: 'dark',
        },
      },
      {
        id: 'fse-13',
        type: 'divider',
        props: {
          type: 'line',
          bgType: 'gradient',
          bgGradientDirection: 'horizontal',
          bgStartColor: 'CBA6F7',
          bgEndColor: '94E2D5',
          bgSolidColor: 'CBA6F7',
          thickness: 2,
          alignment: 'center',
        },
      },
      {
        id: 'fse-14',
        type: 'heading',
        props: {
          text: 'GitHub Stats',
          level: 2,
          alignment: 'center',
          emoji: '📊',
        },
      },
      {
        id: 'fse-15',
        type: 'stats-row',
        props: {
          direction: 'row',
          gap: 12,
          cardWidth: '49%',
          cardHeight: 230,
          theme: 'catppuccin_mocha',
          hideBorder: false,
        },
        children: [
          {
            id: 'fse-15a',
            type: 'stats-card',
            props: {
              username: 'github',
              theme: 'catppuccin_mocha',
              layoutStyle: 'standard',
              showIcons: true,
              hideBorder: false,
              hideTitle: false,
              hideRank: false,
              borderRadius: 12,
              layoutWidth: 'half',
            },
          },
          {
            id: 'fse-15b',
            type: 'top-languages',
            props: {
              username: 'github',
              theme: 'catppuccin_mocha',
              layout: 'compact',
              hideBorder: false,
              hideProgress: false,
              langs_count: 8,
              borderRadius: 12,
              layoutWidth: 'half',
            },
          },
        ],
      },
      {
        id: 'fse-16',
        type: 'streak-stats',
        props: {
          username: 'github',
          theme: 'catppuccin_mocha',
          hideBorder: true,
          borderRadius: 12,
          layoutWidth: 'full',
        },
      },
      {
        id: 'fse-17',
        type: 'activity-graph',
        props: {
          username: 'github',
          theme: 'tokyonight',
          hideBorder: true,
        },
      },
      {
        id: 'fse-18',
        type: 'footer-banner',
        props: {
          text: 'Open to new opportunities',
          type: 'waving',
          section: 'footer',
          height: 120,
          fontSize: 24,
          fontColor: '1E1E2E',
          bgType: 'gradient',
          bgGradientDirection: 'horizontal',
          bgAnimation: 'none',
          bgStartColor: 'CBA6F7',
          bgEndColor: '94E2D5',
          bgSolidColor: 'CBA6F7',
          parallaxEffect: false,
          wavePosition: 70,
          waveAmplitude: 20,
          waveSpeed: 20,
          waveFlip: true,
          textAlignX: 50,
          textAlignY: 66,
        },
      },
    ],
  },

  {
    id: 'data-scientist-ml',
    name: 'Data Scientist / ML Engineer',
    description:
      'ML-focused profile with Python stack, research collapsibles, and a dark scholarly aesthetic',
    thumbnail: '/templates/datascience.png',
    blocks: [
      {
        id: 'ds-1',
        type: 'capsule-header',
        props: {
          text: 'Data Scientist & ML Engineer',
          type: 'soft',
          height: 180,
          section: 'header',
          bgType: 'gradient',
          bgGradientDirection: 'horizontal',
          bgAnimation: 'none',
          bgStartColor: '0A0F0B',
          bgEndColor: '1A2F1B',
          bgSolidColor: '0A0F0B',
          fontColor: 'ffffff',
          fontSize: 30,
          parallaxEffect: false,
          wavePosition: 70,
          waveAmplitude: 20,
          waveSpeed: 20,
          waveFlip: false,
          textAlignX: 50,
          textAlignY: 50,
        },
      },
      {
        id: 'ds-2a',
        type: 'avatar',
        props: {
          imageUrl: 'https://github.com/github.png',
          size: 130,
          borderRadius: 15,
          borderColor: '',
        },
      },
      {
        id: 'ds-2b',
        type: 'greeting',
        props: {
          text: 'Turning data into decisions',
          emoji: '🧠',
          alignment: 'center',
        },
      },
      {
        id: 'ds-3',
        type: 'typing-animation',
        props: {
          lines: [
            'Machine Learning Engineer',
            'Deep Learning · NLP · Computer Vision',
            'Python · PyTorch · TensorFlow',
            'Making models that ship to production',
          ],
          color: 'ABD200',
          width: 520,
          height: 30,
          speed: 50,
        },
      },
      {
        id: 'ds-4',
        type: 'social-badges',
        props: {
          github: 'yourusername',
          linkedin: 'yourusername',
          portfolio: 'https://yoursite.ai',
          email: 'research@yoursite.ai',
          twitter: '',
          youtube: '',
          instagram: '',
          discord: '',
          style: 'for-the-badge',
        },
      },
      {
        id: 'ds-5',
        type: 'divider',
        props: {
          type: 'line',
          bgType: 'solid',
          bgSolidColor: '2D4A2D',
          bgStartColor: '2D4A2D',
          bgEndColor: '2D4A2D',
          bgGradientDirection: 'horizontal',
          thickness: 1,
          alignment: 'center',
        },
      },
      {
        id: 'ds-6',
        type: 'heading',
        props: {
          text: 'What I Work On',
          level: 2,
          alignment: 'left',
          emoji: '🔬',
        },
      },
      {
        id: 'ds-7',
        type: 'paragraph',
        props: {
          text: 'I research and build machine learning systems — from data pipelines and feature engineering to model training, evaluation, and deployment. I bridge the gap between research and production.',
          alignment: 'left',
        },
      },
      {
        id: 'ds-8',
        type: 'collapsible',
        props: { title: '📄 Research & Publications', defaultOpen: true },
        children: [
          {
            id: 'ds-8a',
            type: 'paragraph',
            props: {
              text: '- **[2024]** "Efficient Fine-Tuning of LLMs at Scale" — arxiv.org/abs/xxxx\n- **[2023]** "Real-Time Anomaly Detection in Time-Series Data" — arxiv.org/abs/yyyy\n- **[2022]** "Self-Supervised Representations for Medical Imaging" — NeurIPS Workshop',
              alignment: 'left',
            },
          },
        ],
      },
      {
        id: 'ds-9',
        type: 'collapsible',
        props: { title: '🤖 Featured ML Projects', defaultOpen: false },
        children: [
          {
            id: 'ds-9a',
            type: 'paragraph',
            props: {
              text: '- **llm-fine-tuner** — CLI for LoRA/QLoRA fine-tuning of open-source LLMs\n- **timeseries-bench** — Benchmark suite for time-series forecasting models\n- **cv-pipeline** — Modular computer vision training framework (PyTorch Lightning)',
              alignment: 'left',
            },
          },
        ],
      },
      {
        id: 'ds-10',
        type: 'heading',
        props: {
          text: 'Core Stack',
          level: 2,
          alignment: 'left',
          emoji: '🧰',
        },
      },
      {
        id: 'ds-11',
        type: 'skill-icons',
        props: {
          icons: [
            'python',
            'pytorch',
            'tensorflow',
            'sklearn',
            'opencv',
            'docker',
            'kubernetes',
            'aws',
            'github',
            'linux',
          ],
          perLine: 10,
          theme: 'dark',
        },
      },
      {
        id: 'ds-12',
        type: 'heading',
        props: {
          text: 'Data & Tooling',
          level: 3,
          alignment: 'left',
          emoji: '📦',
        },
      },
      {
        id: 'ds-13',
        type: 'code-block',
        props: {
          language: 'python',
          code: `# A glimpse at my typical experiment setup
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import LoraConfig, get_peft_model

model = AutoModelForCausalLM.from_pretrained("mistralai/Mistral-7B-v0.1")
config = LoraConfig(r=16, lora_alpha=32, target_modules=["q_proj", "v_proj"])
model = get_peft_model(model, config)
print(f"Trainable params: {model.num_parameters(only_trainable=True):,}")`,
        },
      },
      {
        id: 'ds-14',
        type: 'divider',
        props: {
          type: 'line',
          bgType: 'solid',
          bgSolidColor: '2D4A2D',
          bgStartColor: '2D4A2D',
          bgEndColor: '2D4A2D',
          bgGradientDirection: 'horizontal',
          thickness: 1,
          alignment: 'center',
        },
      },
      {
        id: 'ds-15',
        type: 'heading',
        props: {
          text: 'GitHub Activity 📊',
          level: 2,
          alignment: 'center',
          emoji: '',
        },
      },
      {
        id: 'ds-16',
        type: 'stats-row',
        props: {
          direction: 'row',
          gap: 12,
          cardWidth: '49%',
          cardHeight: 230,
          theme: 'merko',
          hideBorder: false,
        },
        children: [
          {
            id: 'ds-16a',
            type: 'stats-card',
            props: {
              username: 'github',
              theme: 'merko',
              layoutStyle: 'standard',
              showIcons: true,
              hideBorder: false,
              hideTitle: false,
              hideRank: false,
              borderRadius: 8,
              layoutWidth: 'half',
            },
          },
          {
            id: 'ds-16b',
            type: 'top-languages',
            props: {
              username: 'github',
              theme: 'merko',
              layout: 'pie',
              hideBorder: false,
              hideProgress: false,
              langs_count: 6,
              borderRadius: 8,
              layoutWidth: 'half',
            },
          },
        ],
      },
      {
        id: 'ds-18',
        type: 'activity-graph',
        props: {
          username: 'github',
          theme: 'merko',
          hideBorder: false,
        },
      },
      {
        id: 'ds-19',
        type: 'quote',
        props: {
          quote: 'In God we trust, all others must bring data.',
          author: 'W. Edwards Deming',
          theme: 'merko',
          textAlign: 'center',
          authorAlign: 'center',
        },
      },
      {
        id: 'ds-20',
        type: 'footer-banner',
        props: {
          text: 'Data-driven. Research-inspired. Production-ready.',
          type: 'waving',
          section: 'footer',
          height: 100,
          fontSize: 24,
          fontColor: 'ABD200',
          bgType: 'gradient',
          bgGradientDirection: 'horizontal',
          bgAnimation: 'none',
          bgStartColor: '0A0F0B',
          bgEndColor: '1A2F1B',
          bgSolidColor: '0A0F0B',
          parallaxEffect: false,
          wavePosition: 70,
          waveAmplitude: 20,
          waveSpeed: 20,
          waveFlip: true,
          textAlignX: 50,
          textAlignY: 72,
        },
      },
    ],
  },

  {
    id: 'devops-cloud',
    name: 'DevOps / Cloud Engineer',
    description:
      'Infrastructure-first profile with a dark terminal aesthetic, badges, and collapsible runbooks',
    thumbnail: '/templates/devops.png',
    blocks: [
      {
        id: 'do-1',
        type: 'capsule-header',
        props: {
          text: 'DevOps & Cloud Engineer',
          type: 'rect',
          height: 160,
          section: 'header',
          bgType: 'gradient',
          bgGradientDirection: 'horizontal',
          bgAnimation: 'none',
          bgStartColor: '0A192F',
          bgEndColor: '112240',
          bgSolidColor: '0A192F',
          fontColor: 'ffffff',
          fontSize: 30,
          parallaxEffect: false,
          wavePosition: 70,
          waveAmplitude: 20,
          waveSpeed: 20,
          waveFlip: false,
          textAlignX: 50,
          textAlignY: 50,
        },
      },
      {
        id: 'do-2',
        type: 'greeting',
        props: {
          text: 'Shipping infra, not just code',
          emoji: '🚀',
          alignment: 'center',
        },
      },
      {
        id: 'do-3',
        type: 'typing-animation',
        props: {
          lines: [
            'Kubernetes · Terraform · AWS',
            'CI/CD Pipelines · GitOps · SRE',
            'Docker · Helm · ArgoCD',
            "99.99% uptime is not a goal — it's a standard",
          ],
          color: '64FFDA',
          width: 520,
          height: 30,
          speed: 50,
          center: true,
          vCenter: true,
        },
      },
      {
        id: 'do-4',
        type: 'social-badges',
        props: {
          github: 'yourusername',
          linkedin: 'yourusername',
          twitter: 'yourusername',
          email: '',
          youtube: '',
          instagram: '',
          discord: '',
          portfolio: '',
          style: 'for-the-badge',
        },
      },
      {
        id: 'do-5',
        type: 'custom-badge',
        props: {
          label: 'AWS',
          message: 'Solutions Architect',
          color: 'FF9900',
          style: 'for-the-badge',
          logo: 'amazon-aws',
        },
      },
      {
        id: 'do-6',
        type: 'divider',
        props: {
          type: 'line',
          bgType: 'solid',
          bgSolidColor: '1C3A5F',
          bgStartColor: '1C3A5F',
          bgEndColor: '1C3A5F',
          bgGradientDirection: 'horizontal',
          thickness: 1,
          alignment: 'center',
        },
      },
      {
        id: 'do-7',
        type: 'heading',
        props: {
          text: 'Core Competencies',
          level: 2,
          alignment: 'left',
          emoji: '🛠️',
        },
      },
      {
        id: 'do-8',
        type: 'paragraph',
        props: {
          text: 'I design, automate, and operate cloud infrastructure at scale. From zero-downtime deployments and multi-region HA clusters to FinOps cost optimisation and security hardening.',
          alignment: 'left',
        },
      },
      {
        id: 'do-9',
        type: 'heading',
        props: {
          text: 'Infrastructure & Cloud',
          level: 3,
          alignment: 'left',
          emoji: '☁️',
        },
      },
      {
        id: 'do-10',
        type: 'skill-icons',
        props: {
          icons: [
            'aws',
            'gcp',
            'azure',
            'docker',
            'kubernetes',
            'nginx',
            'linux',
            'bash',
            'powershell',
            'github',
          ],
          perLine: 10,
          theme: 'dark',
        },
      },
      {
        id: 'do-11',
        type: 'heading',
        props: {
          text: 'Languages & Scripting',
          level: 3,
          alignment: 'left',
          emoji: '💻',
        },
      },
      {
        id: 'do-12',
        type: 'skill-icons',
        props: {
          icons: ['python', 'go', 'ts', 'js', 'rust', 'git', 'vscode', 'vim'],
          perLine: 10,
          theme: 'dark',
        },
      },
      {
        id: 'do-13',
        type: 'collapsible',
        props: { title: '📋 Quick-start: My Kubernetes Boilerplate', defaultOpen: false },
        children: [
          {
            id: 'do-13a',
            type: 'code-block',
            props: {
              language: 'bash',
              code: `# Spin up a local cluster with kind
kind create cluster --config kind-config.yaml

# Install core platform components
helm repo add argo https://argoproj.github.io/argo-helm
helm install argocd argo/argo-cd --namespace argocd --create-namespace

# Bootstrap GitOps repo
kubectl apply -f https://raw.githubusercontent.com/yourusername/platform/main/bootstrap.yaml`,
            },
          },
        ],
      },
      {
        id: 'do-14',
        type: 'collapsible',
        props: { title: '🏗️ Notable Projects', defaultOpen: false },
        children: [
          {
            id: 'do-14a',
            type: 'paragraph',
            props: {
              text: '- **platform-bootstrap** — Production-grade GitOps platform (ArgoCD + Crossplane)\n- **cost-sentinel** — Slack-integrated AWS cost anomaly detection bot (Go)\n- **k8s-hardener** — Automated CIS benchmark enforcement via OPA Gatekeeper',
              alignment: 'left',
            },
          },
        ],
      },
      {
        id: 'do-15',
        type: 'divider',
        props: {
          type: 'line',
          bgType: 'solid',
          bgSolidColor: '1C3A5F',
          bgStartColor: '1C3A5F',
          bgEndColor: '1C3A5F',
          bgGradientDirection: 'horizontal',
          thickness: 1,
          alignment: 'center',
        },
      },
      {
        id: 'do-16',
        type: 'heading',
        props: {
          text: 'GitHub Stats',
          level: 2,
          alignment: 'center',
          emoji: '📈',
        },
      },
      {
        id: 'do-17',
        type: 'stats-card',
        props: {
          username: 'github',
          theme: 'nord',
          layoutStyle: 'standard',
          layoutWidth: 'full',
          showIcons: true,
          hideBorder: false,
          hideTitle: false,
          hideRank: false,
          borderRadius: 8,
        },
      },
      {
        id: 'do-18',
        type: 'streak-stats',
        props: {
          username: 'github',
          theme: 'nord',
          hideBorder: false,
          borderRadius: 8,
          layoutWidth: 'full',
        },
      },
      {
        id: 'do-19',
        type: 'activity-graph',
        props: {
          username: 'github',
          theme: 'react-dark',
          hideBorder: false,
        },
      },
      {
        id: 'do-20',
        type: 'trophies',
        props: {
          username: 'github',
          theme: 'nord',
          column: 6,
          row: 1,
          margin_w: 10,
          margin_h: 10,
          noFrame: true,
          noBg: false,
        },
      },
      {
        id: 'do-21',
        type: 'footer-banner',
        props: {
          text: 'Infrastructure as Code. Culture as Practice.',
          type: 'waving',
          section: 'footer',
          height: 100,
          fontSize: 24,
          fontColor: '64FFDA',
          bgType: 'gradient',
          bgGradientDirection: 'horizontal',
          bgAnimation: 'none',
          bgStartColor: '0A192F',
          bgEndColor: '112240',
          bgSolidColor: '0A192F',
          parallaxEffect: false,
          wavePosition: 70,
          waveAmplitude: 20,
          waveSpeed: 20,
          waveFlip: true,
          textAlignX: 50,
          textAlignY: 68,
        },
      },
    ],
  },

  {
    id: 'student-beginner',
    name: 'Student / Beginner',
    description:
      'A friendly, approachable profile for students and developers who are just starting out',
    thumbnail: '/templates/student.png',
    blocks: [
      {
        id: 'stu-1',
        type: 'capsule-header',
        props: {
          text: 'Learning Every Day!',
          type: 'waving',
          height: 180,
          section: 'header',
          bgType: 'gradient',
          bgGradientDirection: 'horizontal',
          bgAnimation: 'wave',
          bgStartColor: 'FF6B6B',
          bgEndColor: '4ECDC4',
          bgSolidColor: 'FF6B6B',
          fontColor: 'ffffff',
          fontSize: 30,
          parallaxEffect: true,
          wavePosition: 70,
          waveAmplitude: 20,
          waveSpeed: 20,
          waveFlip: true,
          textAlignX: 50,
          textAlignY: 33,
        },
      },
      {
        id: 'stu-2a',
        type: 'avatar',
        props: {
          imageUrl: 'https://github.com/github.png',
          size: 120,
          borderRadius: 50,
          borderColor: '',
        },
      },
      {
        id: 'stu-2b',
        type: 'greeting',
        props: {
          text: "Hi! I'm [Your Name], a CS Student",
          emoji: '🎓',
          alignment: 'center',
        },
      },
      {
        id: 'stu-3',
        type: 'typing-animation',
        props: {
          lines: [
            'CS Student @ [Your University]',
            'Learning to code, one bug at a time 🐛',
            'Building cool stuff with Python & JavaScript',
            'Open to internships & collaborations!',
          ],
          color: 'FF6B6B',
          fontSize: 22,
          width: 460,
          height: 30,
          speed: 50,
          pause: 1000,
          center: true,
          vCenter: true,
        },
      },
      {
        id: 'stu-4',
        type: 'paragraph',
        props: {
          text: "I'm currently in my [Year] year studying Computer Science. I love learning new technologies and building projects that solve real-world problems. When I'm not coding, I enjoy gaming, reading, and hiking.",
          alignment: 'center',
        },
      },
      {
        id: 'stu-5',
        type: 'social-badges',
        props: {
          linkedin: 'yourusername',
          github: 'yourusername',
          email: 'you@student.edu',
          twitter: '',
          youtube: '',
          instagram: '',
          discord: '',
          portfolio: '',
          style: 'flat-square',
        },
      },
      {
        id: 'stu-6',
        type: 'divider',
        props: {
          type: 'line',
          bgType: 'gradient',
          bgGradientDirection: 'horizontal',
          bgStartColor: 'FF6B6B',
          bgEndColor: '4ECDC4',
          bgSolidColor: 'FF6B6B',
          thickness: 2,
          alignment: 'center',
        },
      },
      {
        id: 'stu-7',
        type: 'heading',
        props: {
          text: "What I'm Learning",
          level: 2,
          alignment: 'left',
          emoji: '📚',
        },
      },
      {
        id: 'stu-8',
        type: 'paragraph',
        props: {
          text: '🔭 Currently working on: **My First Portfolio Website**\n🌱 Currently learning: **React, Node.js, and SQL**\n👯 Looking to collaborate on: **Open Source Beginner-Friendly Issues**\n🤔 Looking for help with: **System Design Concepts**\n💬 Ask me about: **Python, HTML/CSS, Algorithms**\n😄 Fun fact: **I once fixed a bug by restarting my computer 😅**',
          alignment: 'left',
        },
      },
      {
        id: 'stu-9',
        type: 'heading',
        props: {
          text: 'Technologies I Know',
          level: 2,
          alignment: 'center',
          emoji: '🛠️',
        },
      },
      {
        id: 'stu-10',
        type: 'skill-icons',
        props: {
          icons: ['html', 'css', 'js', 'python', 'java', 'react', 'git', 'github', 'vscode'],
          perLine: 9,
          theme: 'dark',
        },
      },
      {
        id: 'stu-11',
        type: 'heading',
        props: {
          text: 'Technologies on My Roadmap',
          level: 3,
          alignment: 'center',
          emoji: '🗺️',
        },
      },
      {
        id: 'stu-12',
        type: 'skill-icons',
        props: {
          icons: ['ts', 'nodejs', 'mongodb', 'postgres', 'docker', 'aws'],
          perLine: 6,
          theme: 'dark',
        },
      },
      {
        id: 'stu-13',
        type: 'collapsible',
        props: { title: '🚀 My Projects So Far', defaultOpen: true },
        children: [
          {
            id: 'stu-13a',
            type: 'paragraph',
            props: {
              text: '- **Todo App** — A simple task manager built with React & localStorage\n- **Calculator** — A fully-functional calculator using vanilla JavaScript\n- **Portfolio Site** — My personal portfolio built with HTML, CSS & a little JS\n\n_More coming soon as I keep learning!_',
              alignment: 'left',
            },
          },
        ],
      },
      {
        id: 'stu-14',
        type: 'divider',
        props: {
          type: 'line',
          bgType: 'gradient',
          bgGradientDirection: 'horizontal',
          bgStartColor: 'FF6B6B',
          bgEndColor: '4ECDC4',
          bgSolidColor: 'FF6B6B',
          thickness: 2,
          alignment: 'center',
        },
      },
      {
        id: 'stu-15',
        type: 'heading',
        props: {
          text: 'My GitHub Journey',
          level: 2,
          alignment: 'center',
          emoji: '📊',
        },
      },
      {
        id: 'stu-16',
        type: 'stats-row',
        props: {
          direction: 'row',
          gap: 12,
          cardWidth: '49%',
          cardHeight: 230,
          theme: 'tokyonight',
          hideBorder: false,
        },
        children: [
          {
            id: 'stu-16a',
            type: 'stats-card',
            props: {
              username: 'github',
              theme: 'tokyonight',
              layoutStyle: 'standard',
              showIcons: true,
              hideBorder: false,
              hideTitle: false,
              hideRank: false,
              borderRadius: 10,
              layoutWidth: 'half',
            },
          },
          {
            id: 'stu-16b',
            type: 'top-languages',
            props: {
              username: 'github',
              theme: 'tokyonight',
              layout: 'compact',
              hideBorder: false,
              hideProgress: false,
              langs_count: 6,
              borderRadius: 10,
              layoutWidth: 'half',
            },
          },
        ],
      },
      {
        id: 'stu-18',
        type: 'streak-stats',
        props: {
          username: 'github',
          theme: 'tokyonight',
          hideBorder: false,
          borderRadius: 10,
          layoutWidth: 'full',
        },
      },
      {
        id: 'stu-19',
        type: 'quote',
        props: {
          quote:
            'Education is the passport to the future, for tomorrow belongs to those who prepare for it today.',
          author: 'Malcolm X',
          theme: 'tokyonight',
          textAlign: 'center',
          authorAlign: 'center',
        },
      },
      {
        id: 'stu-20',
        type: 'visitor-counter',
        props: {
          username: 'github',
          color: 'blue',
          style: 'flat',
          label: 'Profile Views',
        },
      },
      {
        id: 'stu-21',
        type: 'footer-banner',
        props: {
          text: 'The best time to start was yesterday. The next best time is now. 🌟',
          type: 'waving',
          section: 'footer',
          height: 120,
          fontSize: 24,
          fontColor: 'ffffff',
          bgType: 'gradient',
          bgGradientDirection: 'horizontal',
          bgAnimation: 'none',
          bgStartColor: 'FF6B6B',
          bgEndColor: '4ECDC4',
          bgSolidColor: 'FF6B6B',
          parallaxEffect: true,
          wavePosition: 70,
          waveAmplitude: 20,
          waveSpeed: 20,
          waveFlip: true,
          textAlignX: 50,
          textAlignY: 73,
        },
      },
    ],
  },

  {
    id: 'cybersecurity-researcher',
    name: 'Cybersecurity Researcher',
    description:
      'Dark, terminal-inspired profile for security professionals with CTF highlights and tool badges',
    thumbnail: '/templates/security.png',
    blocks: [
      {
        id: 'sec-1',
        type: 'capsule-header',
        props: {
          text: '> whoami',
          type: 'rect',
          height: 160,
          section: 'header',
          bgType: 'solid',
          bgSolidColor: '000000',
          bgStartColor: '000000',
          bgEndColor: '0D0D0D',
          bgGradientDirection: 'horizontal',
          bgAnimation: 'none',
          fontColor: '39FF14',
          fontSize: 30,
          parallaxEffect: false,
          wavePosition: 70,
          waveAmplitude: 20,
          waveSpeed: 20,
          waveFlip: false,
          textAlignX: 50,
          textAlignY: 50,
        },
      },
      {
        id: 'sec-2',
        type: 'code-block',
        props: {
          language: 'bash',
          code: `$ whoami
security-researcher

$ cat /etc/skills
[*] Penetration Testing
[*] Malware Analysis & Reverse Engineering
[*] Threat Intelligence & Incident Response
[*] CTF Competitor (Top 1% on HackTheBox)
[*] Bug Bounty Hunter`,
        },
      },
      {
        id: 'sec-3',
        type: 'typing-animation',
        props: {
          lines: [
            'Ethical Hacker & Security Researcher',
            'CTF Player · Bug Bounty Hunter',
            'Red Team · Blue Team · Purple Team',
            'Offensive Security | Defensive Strategy',
          ],
          color: '39FF14',
          width: 500,
          height: 30,
          font: 'Fira Code',
          size: 22,
          duration: 3000,
          pause: 1000,
          center: true,
          vCenter: true,
        },
      },
      {
        id: 'sec-4a',
        type: 'custom-badge',
        props: {
          label: 'HackTheBox',
          message: 'Pro Hacker',
          color: '9FEF00',
          style: 'for-the-badge',
          logo: 'hackthebox',
        },
      },
      {
        id: 'sec-4b',
        type: 'custom-badge',
        props: {
          label: 'TryHackMe',
          message: 'Top 1%',
          color: '212C42',
          style: 'for-the-badge',
          logo: '',
        },
      },
      {
        id: 'sec-4c',
        type: 'custom-badge',
        props: {
          label: 'OSCP',
          message: 'Certified',
          color: 'EF4444',
          style: 'for-the-badge',
          logo: '',
        },
      },
      {
        id: 'sec-5',
        type: 'social-badges',
        props: {
          github: 'yourusername',
          twitter: 'yourusername',
          email: 'pgp@yoursite.io',
          linkedin: '',
          youtube: '',
          instagram: '',
          discord: '',
          portfolio: '',
          style: 'for-the-badge',
          useDefaultStyle: true,
        },
      },
      {
        id: 'sec-6',
        type: 'divider',
        props: {
          type: 'line',
          bgType: 'solid',
          bgSolidColor: '1A1A1A',
          bgStartColor: '1A1A1A',
          bgEndColor: '1A1A1A',
          bgGradientDirection: 'horizontal',
          thickness: 1,
          alignment: 'center',
        },
      },
      {
        id: 'sec-7',
        type: 'heading',
        props: {
          text: 'Arsenal',
          level: 2,
          alignment: 'left',
          emoji: '⚔️',
        },
      },
      {
        id: 'sec-8',
        type: 'skill-icons',
        props: {
          icons: [
            'python',
            'bash',
            'go',
            'rust',
            'c',
            'cpp',
            'linux',
            'docker',
            'github',
            'vscode',
          ],
          perLine: 10,
          theme: 'dark',
        },
      },
      {
        id: 'sec-9',
        type: 'collapsible',
        props: { title: '🚩 CTF Highlights', defaultOpen: true },
        children: [
          {
            id: 'sec-9a',
            type: 'paragraph',
            props: {
              text: '| Competition | Year | Place | Category |\n|---|---|---|---|\n| DEF CON CTF Quals | 2024 | Top 50 | RE / Pwn |\n| HITCON CTF | 2023 | Top 20 | Web / Crypto |\n| Google CTF | 2023 | Top 100 | Misc / Pwn |\n| PicoCTF | 2022 | 1st Place | All |\n\n_Write-ups available on my blog._',
              alignment: 'left',
            },
          },
        ],
      },
      {
        id: 'sec-10',
        type: 'collapsible',
        props: { title: '🔓 Bug Bounty & CVEs', defaultOpen: false },
        children: [
          {
            id: 'sec-10a',
            type: 'paragraph',
            props: {
              text: '- **CVE-2024-XXXXX** — RCE in [Vendor Product] (Critical, CVSS 9.8)\n- **CVE-2023-XXXXX** — Auth bypass in [Open Source Library] (High)\n- **HackerOne** — [Programme Name], $XX,XXX total bounties\n- **Bugcrowd** — Hall of Fame: [Company A], [Company B]',
              alignment: 'left',
            },
          },
        ],
      },
      {
        id: 'sec-11',
        type: 'collapsible',
        props: { title: '🛠️ Public Tools & Research', defaultOpen: false },
        children: [
          {
            id: 'sec-11a',
            type: 'paragraph',
            props: {
              text: '- **reconx** — Automated recon framework for bug bounty hunters (Python)\n- **heap-viz** — Heap visualiser for glibc pwn challenges (C + Python)\n- **mal-sandbox** — Lightweight malware sandbox using Linux namespaces (Go)',
              alignment: 'left',
            },
          },
        ],
      },
      {
        id: 'sec-12',
        type: 'divider',
        props: {
          type: 'line',
          bgType: 'solid',
          bgSolidColor: '1A1A1A',
          bgStartColor: '1A1A1A',
          bgEndColor: '1A1A1A',
          bgGradientDirection: 'horizontal',
          thickness: 1,
          alignment: 'center',
        },
      },
      {
        id: 'sec-13',
        type: 'heading',
        props: {
          text: 'GitHub Activity',
          level: 2,
          alignment: 'center',
          emoji: '📊',
        },
      },
      {
        id: 'sec-14',
        type: 'stats-row',
        props: {
          direction: 'row',
          gap: 12,
          cardWidth: '49%',
          cardHeight: 230,
          theme: 'dark',
          hideBorder: false,
        },
        children: [
          {
            id: 'sec-14a',
            type: 'stats-card',
            props: {
              username: 'github',
              theme: 'dark',
              layoutStyle: 'standard',
              showIcons: true,
              hideBorder: false,
              hideTitle: false,
              hideRank: false,
              borderRadius: 6,
              layoutWidth: 'half',
            },
          },
          {
            id: 'sec-14b',
            type: 'top-languages',
            props: {
              username: 'github',
              theme: 'dark',
              layout: 'compact',
              hideBorder: false,
              hideProgress: false,
              langs_count: 8,
              borderRadius: 6,
              layoutWidth: 'half',
            },
          },
        ],
      },
      {
        id: 'sec-16',
        type: 'activity-graph',
        props: {
          username: 'github',
          theme: 'highcontrast',
          hideBorder: false,
        },
      },
      {
        id: 'sec-17',
        type: 'footer-banner',
        props: {
          text: 'Hack the planet — responsibly.',
          type: 'waving',
          section: 'footer',
          height: 100,
          fontSize: 24,
          fontColor: '39FF14',
          bgType: 'gradient',
          bgGradientDirection: 'horizontal',
          bgAnimation: 'none',
          bgStartColor: '000000',
          bgEndColor: '0D0D0D',
          bgSolidColor: '000000',
        },
      },
    ],
  },

  {
    id: 'game-developer',
    name: 'Game Developer',
    description:
      'Pixel-art inspired layout for indie game developers with engine badges, game collapsibles, and a vibrant Dracula theme',
    thumbnail: '/templates/gamedev.png',
    blocks: [
      {
        id: 'gd-1',
        type: 'capsule-header',
        props: {
          text: 'Game Developer',
          type: 'waving',
          height: 200,
          section: 'header',
          bgType: 'gradient',
          bgGradientDirection: 'horizontal',
          bgAnimation: 'wave',
          bgStartColor: '6272A4',
          bgEndColor: 'FF79C6',
          bgSolidColor: '6272A4',
          fontColor: 'ffffff',
          fontSize: 30,
          parallaxEffect: true,
          wavePosition: 56,
          waveAmplitude: 20,
          waveSpeed: 20,
          waveFlip: true,
          textAlignX: 50,
          textAlignY: 28,
        },
      },
      {
        id: 'gd-2',
        type: 'greeting',
        props: {
          text: 'I make worlds from code 🎮',
          emoji: '🎮',
          alignment: 'center',
        },
      },
      {
        id: 'gd-3',
        type: 'typing-animation',
        props: {
          lines: [
            'Indie Game Developer',
            'Unity · Unreal Engine · Godot',
            'C# · C++ · GDScript',
            'Currently making: [Your Game Title] 🕹️',
          ],
          color: 'BD93F9',
          width: 480,
          height: 30,
          speed: 50,
          duration: 3000,
        },
      },
      {
        id: 'gd-4',
        type: 'paragraph',
        props: {
          text: "I'm an indie game developer obsessed with creating immersive experiences. From game mechanics and level design to shaders and audio — I love every part of the craft.",
          alignment: 'center',
        },
      },
      {
        id: 'gd-5',
        type: 'social-badges',
        props: {
          github: 'yourusername',
          twitter: 'yourusername',
          youtube: 'yourchannel',
          portfolio: 'https://yourgames.itch.io',
          email: 'you@studio.dev',
          linkedin: '',
          instagram: '',
          discord: '',
          style: 'for-the-badge',
        },
      },
      {
        id: 'gd-6a',
        type: 'custom-badge',
        props: {
          label: 'itch.io',
          message: 'Games Published',
          color: 'FA5C5C',
          style: 'for-the-badge',
          logo: '',
        },
      },
      {
        id: 'gd-6b',
        type: 'custom-badge',
        props: {
          label: 'Game Jams',
          message: 'Participated',
          color: 'FFB86C',
          style: 'for-the-badge',
          logo: '',
        },
      },
      {
        id: 'gd-7',
        type: 'divider',
        props: {
          type: 'line',
          bgType: 'gradient',
          bgGradientDirection: 'horizontal',
          bgStartColor: '6272A4',
          bgEndColor: 'FF79C6',
          bgSolidColor: '6272A4',
          thickness: 2,
          alignment: 'center',
        },
      },
      {
        id: 'gd-8',
        type: 'heading',
        props: {
          text: 'Tech & Tools',
          level: 2,
          alignment: 'center',
          emoji: '🧰',
        },
      },
      {
        id: 'gd-9',
        type: 'heading',
        props: {
          text: 'Game Engines & Languages',
          level: 3,
          alignment: 'left',
          emoji: '🕹️',
        },
      },
      {
        id: 'gd-10',
        type: 'skill-icons',
        props: {
          icons: ['unity', 'unreal', 'cs', 'cpp', 'blender', 'figma', 'ps'],
          perLine: 7,
          theme: 'dark',
        },
      },
      {
        id: 'gd-11',
        type: 'heading',
        props: {
          text: 'Dev & Tooling',
          level: 3,
          alignment: 'left',
          emoji: '💻',
        },
      },
      {
        id: 'gd-12',
        type: 'skill-icons',
        props: {
          icons: ['git', 'github', 'vscode', 'python', 'js', 'nodejs', 'docker'],
          perLine: 7,
          theme: 'dark',
        },
      },
      {
        id: 'gd-13',
        type: 'collapsible',
        props: { title: '🎮 Published Games', defaultOpen: true },
        children: [
          {
            id: 'gd-13a',
            type: 'paragraph',
            props: {
              text: '| Game | Engine | Platform | Status |\n|---|---|---|---|\n| **[Game Title 1]** | Unity | PC / Web | Released |\n| **[Game Title 2]** | Godot | PC | Released |\n| **[WIP Game]** | Unreal 5 | PC | In Development |\n\n➡️ Play them all on [itch.io](https://yourusername.itch.io)',
              alignment: 'left',
            },
          },
        ],
      },
      {
        id: 'gd-14',
        type: 'collapsible',
        props: { title: '🏆 Game Jam Highlights', defaultOpen: false },
        children: [
          {
            id: 'gd-14a',
            type: 'paragraph',
            props: {
              text: '- 🥇 **Ludum Dare 54** — "Constraints" — 1st place (Overall)\n- 🥈 **Global Game Jam 2024** — 2nd place (Innovation)\n- 🎖️ **GMTK Game Jam 2023** — Top 5% out of 6,800+ entries',
              alignment: 'left',
            },
          },
        ],
      },
      {
        id: 'gd-15',
        type: 'divider',
        props: {
          type: 'line',
          bgType: 'gradient',
          bgGradientDirection: 'horizontal',
          bgStartColor: '6272A4',
          bgEndColor: 'FF79C6',
          bgSolidColor: '6272A4',
          thickness: 2,
          alignment: 'center',
        },
      },
      {
        id: 'gd-16',
        type: 'heading',
        props: {
          text: 'GitHub Stats',
          level: 2,
          alignment: 'center',
          emoji: '📊',
        },
      },
      {
        id: 'gd-17',
        type: 'stats-row',
        props: {
          direction: 'row',
          gap: 12,
          cardWidth: '49%',
          cardHeight: 230,
          theme: 'dracula',
          hideBorder: false,
        },
        children: [
          {
            id: 'gd-17a',
            type: 'stats-card',
            props: {
              username: 'github',
              theme: 'dracula',
              layoutStyle: 'standard',
              showIcons: true,
              hideBorder: false,
              hideTitle: false,
              hideRank: false,
              borderRadius: 10,
              layoutWidth: 'half',
            },
          },
          {
            id: 'gd-17b',
            type: 'top-languages',
            props: {
              username: 'github',
              theme: 'dracula',
              layout: 'compact',
              hideBorder: false,
              hideProgress: false,
              langs_count: 6,
              borderRadius: 10,
              layoutWidth: 'half',
            },
          },
        ],
      },
      {
        id: 'gd-18',
        type: 'streak-stats',
        props: {
          username: 'github',
          theme: 'dracula',
          hideBorder: false,
          borderRadius: 10,
          layoutWidth: 'full',
        },
      },
      {
        id: 'gd-20',
        type: 'trophies',
        props: {
          username: 'github',
          theme: 'dracula',
          column: 6,
          row: 1,
          margin_w: 10,
          margin_h: 10,
          noFrame: false,
          noBg: false,
        },
      },
      {
        id: 'gd-21',
        type: 'quote',
        props: {
          quote:
            "Every design is a solution to a problem. If you don't understand the problem, you can't design a solution.",
          author: 'Unknown',
          theme: 'dracula',
          textAlign: 'center',
          authorAlign: 'center',
        },
      },
      {
        id: 'gd-22',
        type: 'footer-banner',
        props: {
          text: 'Every great game starts with a single commit.',
          type: 'waving',
          section: 'footer',
          height: 120,
          fontSize: 22,
          fontColor: 'F8F8F2',
          bgType: 'gradient',
          bgGradientDirection: 'horizontal',
          bgAnimation: 'none',
          bgStartColor: '6272A4',
          bgEndColor: 'FF79C6',
          bgSolidColor: '6272A4',
          wavePosition: 70,
          waveAmplitude: 20,
          waveSpeed: 20,
          waveFlip: true,
        },
      },
    ],
  },
];
