name: Auto Approve

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write

jobs:
  auto-approve:
    if: github.event.pull_request.user.login == 'zntb'
    runs-on: ubuntu-latest
    steps:
      - name: Approve PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            })
